artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts\data_ingestion
  source_URL: https://drive.google.com/file/d/11aASTApCu7hfTBvx-i1Ne3XQ9StupCMI/view?usp=sharing
  local_data_file: artifacts\data_ingestion\data.rar
  unzip_dir: artifacts\data_ingestion
